global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Substitua pelo endereço e porta da sua aplicação

  - job_name: 'nova-calculadora'  # Adicione o job para a nova calculadora
    static_configs:
      - targets: ['localhost:9000']  # Substitua pelo endereço e porta da nova calculadora
